version: "3.9"

services:
  user-service:
    build:
      context: .
      dockerfile: Dockerfile
    image: tufailkarim/ecommerce-user-service:latest
    container_name: user-service
    restart: always
    ports:
      - "3000:3000"
    environment:
      - MONGO_URI=mongodb://user-mongo:27017/userdb
      - JWT_SECRET=mySuperSecretKey
      - jwt_expires_in=3600
    depends_on:
      - user-mongo

  user-mongo:
    image: mongo:7
    container_name: user-mongo
    restart: always
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_DATABASE=userdb
    volumes:
      - user_mongo_data:/data/db

volumes:
  user_mongo_data:
